name: areaweb-framework
recipe: lemp
config:
  via: nginx
  config:
    vhosts: .lando/nginx.conf
  php: '8.2'
  composer_version: '2.2.12'
  database: mariadb
services:
  phpmyadmin:
    type: phpmyadmin
